Repository SUSE/doc-cap, pull requests merged in 2020-01, with the labels that each got.

#657 Update Metrics content to match Github README
  xml/cap_depl_stratos.xml
Labels: 1.5 Applicable, 1.5.1 Applicable

#658 SES not included. Remove mention
  xml/cap_overview.xml
Labels: 1.4.1 Applicable, 1.5 Applicable, 1.5.1 Applicable

#661 Add parameter for default SCF namespace.
  xml/cap_depl_stratos.xml
  xml/repeated-content-decl.ent
Labels: 1.4.1 Applicable, 1.5 Applicable, 1.5.1 Applicable

#664 Minibroker service DB & app versions are for <= K8s 1.15
  xml/cap_admin_service_broker.xml
Labels: 1.4.1 Applicable, 1.5 Applicable, 1.5.1 Applicable

#668 External db only during deployment
  xml/cap_admin_external_db.xml
Labels: 1.5.1 Applicable

#672 Example should refer to only config file and not CLI too
  xml/cap_depl_ha.xml
Labels: 1.5 Applicable, 1.5.1 Applicable

#673 Embedded UAA is compatible with Ingress Controller in 1.5.1
  xml/repeated-content-decl.ent
Labels: 1.5.1 Applicable

#677 Privleged on kubelet only for Kube < 1.15
  xml/cap_kube_requirements.xml
Labels: 1.4.1 Applicable, 1.5 Applicable, 1.5.1 Applicable

#683 Add branching change info to README
  README.adoc
Labels: 1.4.1 Applicable, 1.5 Applicable, 1.5.1 Applicable

#685 Update console and metrics versions
  xml/entity-decl.ent
Labels: 1.5.1 Applicable
