Repository SUSE/doc-cap, pull requests merged in 2020-03, with the labels that each got.

#738 Update messaging around Helm 2 & 3
  xml/cap_depl_install_caasp.xml
  xml/cap_kube_requirements.xml
  xml/repeated-content-decl.ent
Labels: 1.5.1, 1.5.2

#739 Remove Openstack chapter. Point to CaaSP docs
  xml/book_cap_guides.xml
  xml/cap_depl_openstack.xml
Labels: 1.4.1, 1.5, 1.5.1, 1.5.2, 2.0

#741 Update to use Helm 3 syntax
  xml/cap_admin_app_domains.xml
  xml/cap_admin_certificates.xml
  xml/cap_admin_credhub.xml
  xml/cap_admin_nproc_limits.xml
  xml/cap_admin_service_broker.xml
  xml/cap_admin_upgrade.xml
  xml/cap_depl_aks.xml
  xml/cap_depl_eirini.xml
  xml/cap_depl_eks.xml
  xml/cap_depl_gke.xml
  xml/cap_depl_ha.xml
  xml/cap_depl_ingress.xml
  xml/cap_depl_install_caasp.xml
  xml/cap_depl_stratos.xml
Labels: 2.0

#747 Replace services diagrams with SVG format
  images/src/png/cap-detailed-services.png
  images/src/png/cap-simple-services.png
  images/src/svg/cap-detailed-services.svg
  images/src/svg/cap-simple-services.svg
  xml/cap_overview.xml
Labels: 1.4.1, 1.5, 1.5.1, 1.5.2, 2.0

#737 Update CaaSP system requirements
  xml/cap_depl_install_caasp.xml
Labels: 1.5, 1.5.1, 1.5.2

#751 Remove unneeded content and insert some TODO placeholders
  xml/app_psps.xml
  xml/app_scf_values_yaml.xml
  xml/app_uaa_values_yaml.xml
  xml/appendix.xml
  xml/book_cap_guides.xml
  xml/cap_admin_app_autoscaler.xml
  xml/cap_admin_app_domains.xml
  xml/cap_admin_backup-restore.xml
  xml/cap_admin_ccdb_key_rotation.xml
  xml/cap_admin_certificates.xml
  xml/cap_admin_configuration_changes.xml
  xml/cap_admin_credhub.xml
  xml/cap_admin_nproc_limits.xml
  xml/cap_admin_service_broker.xml
  xml/cap_admin_upgrade.xml
  xml/cap_depl_admin_notes.xml
  xml/cap_depl_air_gap_registry.xml
  xml/cap_depl_aks.xml
  xml/cap_depl_caasp.xml
  xml/cap_depl_eirini.xml
  xml/cap_depl_eks.xml
  xml/cap_depl_gke.xml
  xml/cap_depl_ha.xml
  xml/cap_depl_ingress.xml
  xml/cap_depl_stratos.xml
  xml/cap_overview.xml
  xml/cap_troubleshooting.xml
  xml/repeated-content-decl.ent
Labels: 2.0

#753 Update links to Helm docs
  xml/cap_depl_caasp.xml
  xml/repeated-content-decl.ent
Labels: 2.0

#754 Update messaging about using Helm 3 and remove Tiller mentions
  xml/cap_depl_aks.xml
  xml/cap_depl_caasp.xml
  xml/cap_depl_eks.xml
  xml/cap_depl_gke.xml
  xml/cap_kube_requirements.xml
  xml/cap_overview.xml
  xml/entity-decl.ent
  xml/repeated-content-decl.ent
Labels: 2.0

#762 Add section to troubleshooting MySQL
  xml/cap_troubleshooting.xml
Labels: 1.5, 1.5.1, 1.5.2

#767 Update entity values
  xml/entity-decl.ent
Labels: 2.0

#768 Update Minibroker charts versions.
  xml/cap_admin_service_broker.xml
Labels: 2.0
