Repository SUSE/doc-cap, pull requests merged in 2020-08, with the labels that each got.

#921 Fix incoherent sentence and update helm inspect -> show
  xml/repeated-content-decl.ent
Labels: 2.0

#920 Fix consistency with example value
  xml/repeated-content-decl.ent
Labels: 2.0

#919 Update phrasing to indicate Helm 3 is requirement
  xml/repeated-content-decl.ent
Labels: 2.0

#925 Add .editorconfig to maintain file format consistency
  .editorconfig
Labels: 1.5.2, 2.0

#924 Use example.com as system domain
  xml/repeated-content-decl.ent
Labels: 2.0

#931 Typo
  xml/repeated-content-decl.ent
Labels: 2.0

#933 Fix alignment of helm search repo output
  xml/repeated-content-decl.ent
Labels: 2.0

#936 Update scheduler definition.
  xml/cap_overview.xml
Labels: 2.0

#950 Fix ref to scf
  xml/repeated-content-decl.ent
Labels: 2.0

#955 Add affinity/anti-affinity section
  xml/cap_depl_aks.xml
  xml/cap_depl_caasp.xml
  xml/cap_depl_eks.xml
  xml/cap_depl_gke.xml
  xml/repeated-content-decl.ent
Labels: 2.0.1

#947 Update kubecf appendix. Add back cf-operator appendix
  xml/app_cf_operator_values_yaml.xml
  xml/app_kubecf_values_yaml.xml
  xml/appendix.xml
Labels: 2.0.1

#941 2.0.1 version numbers
  xml/entity-decl.ent
  xml/repeated-content-decl.ent
Labels: 2.0.1

#949 Update upgrade steps for 2.0.1
  xml/cap_admin_upgrade.xml
Labels: 2.0.1

#951 Re-enable external database section
  xml/repeated-content-decl.ent
Labels: 2.0.1
